export const choiceThemes = {
  courage: {
    label: 'Courage',
    hint: 'A step into uncertainty',
    color: '#d68b7c',
    rgb: '154, 57, 50',
  },
  connection: {
    label: 'Connection',
    hint: 'Let someone into the story',
    color: '#e2a6b6',
    rgb: '160, 77, 104',
  },
  comfort: {
    label: 'Comfort',
    hint: 'Protect a little peace',
    color: '#a1c5ab',
    rgb: '71, 126, 91',
  },
  curiosity: {
    label: 'Discovery',
    hint: 'Follow what you don’t know yet',
    color: '#afb4e9',
    rgb: '91, 91, 166',
  },
  commitment: {
    label: 'Devotion',
    hint: 'Give something your time',
    color: '#e0c28d',
    rgb: '157, 115, 56',
  },
  freedom: {
    label: 'Independence',
    hint: 'Make room for your own rhythm',
    color: '#90c7c5',
    rgb: '48, 121, 132',
  },
  release: {
    label: 'Letting go',
    hint: 'Leave space for what comes next',
    color: '#c2aed2',
    rgb: '116, 84, 140',
  },
} as const;
export type ChoiceTheme = keyof typeof choiceThemes;
// Editorial choices, not sentiment guesses or good/bad outcome predictions.
export const eventChoiceThemes: Record<
  string,
  [ChoiceTheme, ChoiceTheme, ChoiceTheme]
> = {
  'empty-chair': ['courage', 'connection', 'freedom'],
  'small-secret': ['connection', 'commitment', 'connection'],
  'old-camera': ['courage', 'connection', 'comfort'],
  'small-stage': ['courage', 'commitment', 'connection'],
  'home-change': ['curiosity', 'connection', 'comfort'],
  'new-face': ['connection', 'curiosity', 'comfort'],
  'first-pay': ['commitment', 'comfort', 'freedom'],
  'after-school': ['curiosity', 'commitment', 'freedom'],
  'last-summer': ['curiosity', 'commitment', 'freedom'],
  'different-opinion': ['courage', 'curiosity', 'comfort'],
  'friend-distance': ['connection', 'courage', 'release'],
  'first-failure': ['courage', 'connection', 'comfort'],
  'open-door': ['commitment', 'curiosity', 'freedom'],
  'new-city': ['courage', 'curiosity', 'commitment'],
  'dinner-invitation': ['connection', 'connection', 'comfort'],
  'unfinished-song': ['commitment', 'connection', 'freedom'],
  budget: ['comfort', 'curiosity', 'commitment'],
  'quiet-love': ['courage', 'connection', 'comfort'],
  qualification: ['courage', 'connection', 'comfort'],
  roots: ['comfort', 'connection', 'freedom'],
  'work-crossroad': ['courage', 'freedom', 'comfort'],
  'small-business': ['courage', 'connection', 'comfort'],
  'parenthood-question': ['commitment', 'connection', 'freedom'],
  'return-friend': ['connection', 'commitment', 'release'],
  'body-message': ['comfort', 'connection', 'comfort'],
  promise: ['commitment', 'connection', 'comfort'],
  hours: ['freedom', 'connection', 'comfort'],
  mentor: ['commitment', 'connection', 'courage'],
  'distance-care': ['commitment', 'connection', 'comfort'],
  'other-skill': ['courage', 'connection', 'curiosity'],
  'long-trip': ['courage', 'connection', 'curiosity'],
  neighborhood: ['commitment', 'connection', 'comfort'],
  'relationship-space': ['courage', 'connection', 'release'],
  'old-ambition': ['courage', 'connection', 'release'],
  enough: ['commitment', 'freedom', 'comfort'],
  'family-stories': ['commitment', 'curiosity', 'connection'],
  'making-room': ['comfort', 'release', 'comfort'],
  'new-ritual': ['commitment', 'connection', 'freedom'],
  'home-again': ['curiosity', 'connection', 'freedom'],
  exhibition: ['courage', 'connection', 'freedom'],
  expertise: ['commitment', 'connection', 'commitment'],
  'friend-ritual': ['commitment', 'connection', 'freedom'],
  'change-work': ['courage', 'release', 'comfort'],
  'body-care': ['curiosity', 'connection', 'release'],
  'unexpected-free': ['curiosity', 'connection', 'comfort'],
  garden: ['commitment', 'connection', 'comfort'],
  retirement: ['release', 'commitment', 'comfort'],
  'local-table': ['courage', 'connection', 'commitment'],
  'learning-late': ['courage', 'connection', 'curiosity'],
  'old-travel': ['curiosity', 'connection', 'comfort'],
  'passing-on': ['release', 'connection', 'commitment'],
  'ordinary-joy': ['curiosity', 'connection', 'comfort'],
  'memory-box': ['curiosity', 'connection', 'comfort'],
  help: ['courage', 'connection', 'freedom'],
  unfinished: ['courage', 'connection', 'release'],
  'late-friend': ['courage', 'connection', 'freedom'],
  window: ['commitment', 'connection', 'comfort'],
  letter: ['comfort', 'connection', 'freedom'],
};
